#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Jun 11 10:25:22 EDT 2021
# SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim VIP_RelationalCache_behav -key {Behavioral:sim_1:Functional:VIP_RelationalCache} -tclbatch VIP_RelationalCache.tcl -view /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/TB_read_write_master_behav.wcfg -log simulate.log
