-- Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2017.4 (lin64) Build 2086221 Fri Dec 15 20:54:30 MST 2017
-- Date        : Mon Mar 22 09:43:36 2021
-- Host        : buflightdev running 64-bit Ubuntu 16.04.7 LTS
-- Command     : write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_2_BRAM_Splitter_0_0_sim_netlist.vhdl
-- Design      : design_2_BRAM_Splitter_0_0
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xczu9eg-ffvb1156-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;
entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  port (
    bram_rst_a_in : in STD_LOGIC;
    bram_clk_a_in : in STD_LOGIC;
    bram_en_a_in : in STD_LOGIC;
    bram_we_a_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_addr_a_in : in STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_din_a_in : in STD_LOGIC_VECTOR ( 127 downto 0 );
    bram_dout_a_in : out STD_LOGIC_VECTOR ( 127 downto 0 );
    bram_rst_b_in : in STD_LOGIC;
    bram_clk_b_in : in STD_LOGIC;
    bram_en_b_in : in STD_LOGIC;
    bram_we_b_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_addr_b_in : in STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_din_b_in : in STD_LOGIC_VECTOR ( 127 downto 0 );
    bram_dout_b_in : out STD_LOGIC_VECTOR ( 127 downto 0 );
    bram_rst_a_out_0 : out STD_LOGIC;
    bram_clk_a_out_0 : out STD_LOGIC;
    bram_en_a_out_0 : out STD_LOGIC;
    bram_we_a_out_0 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    bram_addr_a_out_0 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_dout_a_out_0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_din_a_out_0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_rst_b_out_0 : out STD_LOGIC;
    bram_clk_b_out_0 : out STD_LOGIC;
    bram_en_b_out_0 : out STD_LOGIC;
    bram_we_b_out_0 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    bram_addr_b_out_0 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_dout_b_out_0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_din_b_out_0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_rst_a_out_1 : out STD_LOGIC;
    bram_clk_a_out_1 : out STD_LOGIC;
    bram_en_a_out_1 : out STD_LOGIC;
    bram_we_a_out_1 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    bram_addr_a_out_1 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_dout_a_out_1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_din_a_out_1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_rst_b_out_1 : out STD_LOGIC;
    bram_clk_b_out_1 : out STD_LOGIC;
    bram_en_b_out_1 : out STD_LOGIC;
    bram_we_b_out_1 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    bram_addr_b_out_1 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_dout_b_out_1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_din_b_out_1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_rst_a_out_2 : out STD_LOGIC;
    bram_clk_a_out_2 : out STD_LOGIC;
    bram_en_a_out_2 : out STD_LOGIC;
    bram_we_a_out_2 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    bram_addr_a_out_2 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_dout_a_out_2 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_din_a_out_2 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_rst_b_out_2 : out STD_LOGIC;
    bram_clk_b_out_2 : out STD_LOGIC;
    bram_en_b_out_2 : out STD_LOGIC;
    bram_we_b_out_2 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    bram_addr_b_out_2 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_dout_b_out_2 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_din_b_out_2 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_rst_a_out_3 : out STD_LOGIC;
    bram_clk_a_out_3 : out STD_LOGIC;
    bram_en_a_out_3 : out STD_LOGIC;
    bram_we_a_out_3 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    bram_addr_a_out_3 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_dout_a_out_3 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_din_a_out_3 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_rst_b_out_3 : out STD_LOGIC;
    bram_clk_b_out_3 : out STD_LOGIC;
    bram_en_b_out_3 : out STD_LOGIC;
    bram_we_b_out_3 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    bram_addr_b_out_3 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_dout_b_out_3 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_din_b_out_3 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_rst_a_out_4 : out STD_LOGIC;
    bram_clk_a_out_4 : out STD_LOGIC;
    bram_en_a_out_4 : out STD_LOGIC;
    bram_we_a_out_4 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    bram_addr_a_out_4 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_dout_a_out_4 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_din_a_out_4 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_rst_b_out_4 : out STD_LOGIC;
    bram_clk_b_out_4 : out STD_LOGIC;
    bram_en_b_out_4 : out STD_LOGIC;
    bram_we_b_out_4 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    bram_addr_b_out_4 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_dout_b_out_4 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_din_b_out_4 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_rst_a_out_5 : out STD_LOGIC;
    bram_clk_a_out_5 : out STD_LOGIC;
    bram_en_a_out_5 : out STD_LOGIC;
    bram_we_a_out_5 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    bram_addr_a_out_5 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_dout_a_out_5 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_din_a_out_5 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_rst_b_out_5 : out STD_LOGIC;
    bram_clk_b_out_5 : out STD_LOGIC;
    bram_en_b_out_5 : out STD_LOGIC;
    bram_we_b_out_5 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    bram_addr_b_out_5 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_dout_b_out_5 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_din_b_out_5 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_rst_a_out_6 : out STD_LOGIC;
    bram_clk_a_out_6 : out STD_LOGIC;
    bram_en_a_out_6 : out STD_LOGIC;
    bram_we_a_out_6 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    bram_addr_a_out_6 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_dout_a_out_6 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_din_a_out_6 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_rst_b_out_6 : out STD_LOGIC;
    bram_clk_b_out_6 : out STD_LOGIC;
    bram_en_b_out_6 : out STD_LOGIC;
    bram_we_b_out_6 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    bram_addr_b_out_6 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_dout_b_out_6 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_din_b_out_6 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_rst_a_out_7 : out STD_LOGIC;
    bram_clk_a_out_7 : out STD_LOGIC;
    bram_en_a_out_7 : out STD_LOGIC;
    bram_we_a_out_7 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    bram_addr_a_out_7 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_dout_a_out_7 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_din_a_out_7 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_rst_b_out_7 : out STD_LOGIC;
    bram_clk_b_out_7 : out STD_LOGIC;
    bram_en_b_out_7 : out STD_LOGIC;
    bram_we_b_out_7 : out STD_LOGIC_VECTOR ( 1 downto 0 );
    bram_addr_b_out_7 : out STD_LOGIC_VECTOR ( 39 downto 0 );
    bram_dout_b_out_7 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    bram_din_b_out_7 : out STD_LOGIC_VECTOR ( 15 downto 0 )
  );
  attribute NotValidForBitStream : boolean;
  attribute NotValidForBitStream of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is true;
  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "design_2_BRAM_Splitter_0_0,BRAM_Splitter,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "BRAM_Splitter,Vivado 2017.4";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture STRUCTURE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  signal \^bram_addr_a_in\ : STD_LOGIC_VECTOR ( 39 downto 0 );
  signal \^bram_addr_b_in\ : STD_LOGIC_VECTOR ( 39 downto 0 );
  signal \^bram_clk_a_in\ : STD_LOGIC;
  signal \^bram_clk_b_in\ : STD_LOGIC;
  signal \^bram_din_a_in\ : STD_LOGIC_VECTOR ( 127 downto 0 );
  signal \^bram_din_b_in\ : STD_LOGIC_VECTOR ( 127 downto 0 );
  signal \^bram_dout_a_out_0\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^bram_dout_a_out_1\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^bram_dout_a_out_2\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^bram_dout_a_out_3\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^bram_dout_a_out_4\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^bram_dout_a_out_5\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^bram_dout_a_out_6\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^bram_dout_a_out_7\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^bram_dout_b_out_0\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^bram_dout_b_out_1\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^bram_dout_b_out_2\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^bram_dout_b_out_3\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^bram_dout_b_out_4\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^bram_dout_b_out_5\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^bram_dout_b_out_6\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^bram_dout_b_out_7\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^bram_en_a_in\ : STD_LOGIC;
  signal \^bram_en_b_in\ : STD_LOGIC;
  signal \^bram_rst_a_in\ : STD_LOGIC;
  signal \^bram_rst_b_in\ : STD_LOGIC;
  signal \^bram_we_a_in\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  signal \^bram_we_b_in\ : STD_LOGIC_VECTOR ( 15 downto 0 );
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of bram_clk_a_in : signal is "xilinx.com:interface:bram:1.0 bram_a_in CLK";
  attribute X_INTERFACE_INFO of bram_clk_a_out_0 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_0 CLK";
  attribute X_INTERFACE_INFO of bram_clk_a_out_1 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_1 CLK";
  attribute X_INTERFACE_INFO of bram_clk_a_out_2 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_2 CLK";
  attribute X_INTERFACE_INFO of bram_clk_a_out_3 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_3 CLK";
  attribute X_INTERFACE_INFO of bram_clk_a_out_4 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_4 CLK";
  attribute X_INTERFACE_INFO of bram_clk_a_out_5 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_5 CLK";
  attribute X_INTERFACE_INFO of bram_clk_a_out_6 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_6 CLK";
  attribute X_INTERFACE_INFO of bram_clk_a_out_7 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_7 CLK";
  attribute X_INTERFACE_INFO of bram_clk_b_in : signal is "xilinx.com:interface:bram:1.0 bram_b_in CLK";
  attribute X_INTERFACE_INFO of bram_clk_b_out_0 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_0 CLK";
  attribute X_INTERFACE_INFO of bram_clk_b_out_1 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_1 CLK";
  attribute X_INTERFACE_INFO of bram_clk_b_out_2 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_2 CLK";
  attribute X_INTERFACE_INFO of bram_clk_b_out_3 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_3 CLK";
  attribute X_INTERFACE_INFO of bram_clk_b_out_4 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_4 CLK";
  attribute X_INTERFACE_INFO of bram_clk_b_out_5 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_5 CLK";
  attribute X_INTERFACE_INFO of bram_clk_b_out_6 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_6 CLK";
  attribute X_INTERFACE_INFO of bram_clk_b_out_7 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_7 CLK";
  attribute X_INTERFACE_INFO of bram_en_a_in : signal is "xilinx.com:interface:bram:1.0 bram_a_in EN";
  attribute X_INTERFACE_INFO of bram_en_a_out_0 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_0 EN";
  attribute X_INTERFACE_INFO of bram_en_a_out_1 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_1 EN";
  attribute X_INTERFACE_INFO of bram_en_a_out_2 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_2 EN";
  attribute X_INTERFACE_INFO of bram_en_a_out_3 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_3 EN";
  attribute X_INTERFACE_INFO of bram_en_a_out_4 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_4 EN";
  attribute X_INTERFACE_INFO of bram_en_a_out_5 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_5 EN";
  attribute X_INTERFACE_INFO of bram_en_a_out_6 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_6 EN";
  attribute X_INTERFACE_INFO of bram_en_a_out_7 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_7 EN";
  attribute X_INTERFACE_INFO of bram_en_b_in : signal is "xilinx.com:interface:bram:1.0 bram_b_in EN";
  attribute X_INTERFACE_INFO of bram_en_b_out_0 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_0 EN";
  attribute X_INTERFACE_INFO of bram_en_b_out_1 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_1 EN";
  attribute X_INTERFACE_INFO of bram_en_b_out_2 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_2 EN";
  attribute X_INTERFACE_INFO of bram_en_b_out_3 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_3 EN";
  attribute X_INTERFACE_INFO of bram_en_b_out_4 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_4 EN";
  attribute X_INTERFACE_INFO of bram_en_b_out_5 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_5 EN";
  attribute X_INTERFACE_INFO of bram_en_b_out_6 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_6 EN";
  attribute X_INTERFACE_INFO of bram_en_b_out_7 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_7 EN";
  attribute X_INTERFACE_INFO of bram_rst_a_in : signal is "xilinx.com:interface:bram:1.0 bram_a_in RST";
  attribute X_INTERFACE_INFO of bram_rst_a_out_0 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_0 RST";
  attribute X_INTERFACE_INFO of bram_rst_a_out_1 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_1 RST";
  attribute X_INTERFACE_INFO of bram_rst_a_out_2 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_2 RST";
  attribute X_INTERFACE_INFO of bram_rst_a_out_3 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_3 RST";
  attribute X_INTERFACE_INFO of bram_rst_a_out_4 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_4 RST";
  attribute X_INTERFACE_INFO of bram_rst_a_out_5 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_5 RST";
  attribute X_INTERFACE_INFO of bram_rst_a_out_6 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_6 RST";
  attribute X_INTERFACE_INFO of bram_rst_a_out_7 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_7 RST";
  attribute X_INTERFACE_INFO of bram_rst_b_in : signal is "xilinx.com:interface:bram:1.0 bram_b_in RST";
  attribute X_INTERFACE_INFO of bram_rst_b_out_0 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_0 RST";
  attribute X_INTERFACE_INFO of bram_rst_b_out_1 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_1 RST";
  attribute X_INTERFACE_INFO of bram_rst_b_out_2 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_2 RST";
  attribute X_INTERFACE_INFO of bram_rst_b_out_3 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_3 RST";
  attribute X_INTERFACE_INFO of bram_rst_b_out_4 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_4 RST";
  attribute X_INTERFACE_INFO of bram_rst_b_out_5 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_5 RST";
  attribute X_INTERFACE_INFO of bram_rst_b_out_6 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_6 RST";
  attribute X_INTERFACE_INFO of bram_rst_b_out_7 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_7 RST";
  attribute X_INTERFACE_INFO of bram_addr_a_in : signal is "xilinx.com:interface:bram:1.0 bram_a_in ADDR";
  attribute X_INTERFACE_INFO of bram_addr_a_out_0 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_0 ADDR";
  attribute X_INTERFACE_INFO of bram_addr_a_out_1 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_1 ADDR";
  attribute X_INTERFACE_INFO of bram_addr_a_out_2 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_2 ADDR";
  attribute X_INTERFACE_INFO of bram_addr_a_out_3 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_3 ADDR";
  attribute X_INTERFACE_INFO of bram_addr_a_out_4 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_4 ADDR";
  attribute X_INTERFACE_INFO of bram_addr_a_out_5 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_5 ADDR";
  attribute X_INTERFACE_INFO of bram_addr_a_out_6 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_6 ADDR";
  attribute X_INTERFACE_INFO of bram_addr_a_out_7 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_7 ADDR";
  attribute X_INTERFACE_INFO of bram_addr_b_in : signal is "xilinx.com:interface:bram:1.0 bram_b_in ADDR";
  attribute X_INTERFACE_INFO of bram_addr_b_out_0 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_0 ADDR";
  attribute X_INTERFACE_INFO of bram_addr_b_out_1 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_1 ADDR";
  attribute X_INTERFACE_INFO of bram_addr_b_out_2 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_2 ADDR";
  attribute X_INTERFACE_INFO of bram_addr_b_out_3 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_3 ADDR";
  attribute X_INTERFACE_INFO of bram_addr_b_out_4 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_4 ADDR";
  attribute X_INTERFACE_INFO of bram_addr_b_out_5 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_5 ADDR";
  attribute X_INTERFACE_INFO of bram_addr_b_out_6 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_6 ADDR";
  attribute X_INTERFACE_INFO of bram_addr_b_out_7 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_7 ADDR";
  attribute X_INTERFACE_INFO of bram_din_a_in : signal is "xilinx.com:interface:bram:1.0 bram_a_in DIN";
  attribute X_INTERFACE_INFO of bram_din_a_out_0 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_0 DIN";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of bram_din_a_out_0 : signal is "XIL_INTERFACENAME bram_a_out_0, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_din_a_out_1 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_1 DIN";
  attribute X_INTERFACE_PARAMETER of bram_din_a_out_1 : signal is "XIL_INTERFACENAME bram_a_out_1, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_din_a_out_2 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_2 DIN";
  attribute X_INTERFACE_PARAMETER of bram_din_a_out_2 : signal is "XIL_INTERFACENAME bram_a_out_2, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_din_a_out_3 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_3 DIN";
  attribute X_INTERFACE_PARAMETER of bram_din_a_out_3 : signal is "XIL_INTERFACENAME bram_a_out_3, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_din_a_out_4 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_4 DIN";
  attribute X_INTERFACE_PARAMETER of bram_din_a_out_4 : signal is "XIL_INTERFACENAME bram_a_out_4, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_din_a_out_5 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_5 DIN";
  attribute X_INTERFACE_PARAMETER of bram_din_a_out_5 : signal is "XIL_INTERFACENAME bram_a_out_5, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_din_a_out_6 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_6 DIN";
  attribute X_INTERFACE_PARAMETER of bram_din_a_out_6 : signal is "XIL_INTERFACENAME bram_a_out_6, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_din_a_out_7 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_7 DIN";
  attribute X_INTERFACE_PARAMETER of bram_din_a_out_7 : signal is "XIL_INTERFACENAME bram_a_out_7, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_din_b_in : signal is "xilinx.com:interface:bram:1.0 bram_b_in DIN";
  attribute X_INTERFACE_INFO of bram_din_b_out_0 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_0 DIN";
  attribute X_INTERFACE_PARAMETER of bram_din_b_out_0 : signal is "XIL_INTERFACENAME bram_b_out_0, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_din_b_out_1 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_1 DIN";
  attribute X_INTERFACE_PARAMETER of bram_din_b_out_1 : signal is "XIL_INTERFACENAME bram_b_out_1, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_din_b_out_2 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_2 DIN";
  attribute X_INTERFACE_PARAMETER of bram_din_b_out_2 : signal is "XIL_INTERFACENAME bram_b_out_2, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_din_b_out_3 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_3 DIN";
  attribute X_INTERFACE_PARAMETER of bram_din_b_out_3 : signal is "XIL_INTERFACENAME bram_b_out_3, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_din_b_out_4 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_4 DIN";
  attribute X_INTERFACE_PARAMETER of bram_din_b_out_4 : signal is "XIL_INTERFACENAME bram_b_out_4, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_din_b_out_5 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_5 DIN";
  attribute X_INTERFACE_PARAMETER of bram_din_b_out_5 : signal is "XIL_INTERFACENAME bram_b_out_5, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_din_b_out_6 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_6 DIN";
  attribute X_INTERFACE_PARAMETER of bram_din_b_out_6 : signal is "XIL_INTERFACENAME bram_b_out_6, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_din_b_out_7 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_7 DIN";
  attribute X_INTERFACE_PARAMETER of bram_din_b_out_7 : signal is "XIL_INTERFACENAME bram_b_out_7, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_dout_a_in : signal is "xilinx.com:interface:bram:1.0 bram_a_in DOUT";
  attribute X_INTERFACE_PARAMETER of bram_dout_a_in : signal is "XIL_INTERFACENAME bram_a_in, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_dout_a_out_0 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_0 DOUT";
  attribute X_INTERFACE_INFO of bram_dout_a_out_1 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_1 DOUT";
  attribute X_INTERFACE_INFO of bram_dout_a_out_2 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_2 DOUT";
  attribute X_INTERFACE_INFO of bram_dout_a_out_3 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_3 DOUT";
  attribute X_INTERFACE_INFO of bram_dout_a_out_4 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_4 DOUT";
  attribute X_INTERFACE_INFO of bram_dout_a_out_5 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_5 DOUT";
  attribute X_INTERFACE_INFO of bram_dout_a_out_6 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_6 DOUT";
  attribute X_INTERFACE_INFO of bram_dout_a_out_7 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_7 DOUT";
  attribute X_INTERFACE_INFO of bram_dout_b_in : signal is "xilinx.com:interface:bram:1.0 bram_b_in DOUT";
  attribute X_INTERFACE_PARAMETER of bram_dout_b_in : signal is "XIL_INTERFACENAME bram_b_in, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_WRITE_MODE READ_WRITE";
  attribute X_INTERFACE_INFO of bram_dout_b_out_0 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_0 DOUT";
  attribute X_INTERFACE_INFO of bram_dout_b_out_1 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_1 DOUT";
  attribute X_INTERFACE_INFO of bram_dout_b_out_2 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_2 DOUT";
  attribute X_INTERFACE_INFO of bram_dout_b_out_3 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_3 DOUT";
  attribute X_INTERFACE_INFO of bram_dout_b_out_4 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_4 DOUT";
  attribute X_INTERFACE_INFO of bram_dout_b_out_5 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_5 DOUT";
  attribute X_INTERFACE_INFO of bram_dout_b_out_6 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_6 DOUT";
  attribute X_INTERFACE_INFO of bram_dout_b_out_7 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_7 DOUT";
  attribute X_INTERFACE_INFO of bram_we_a_in : signal is "xilinx.com:interface:bram:1.0 bram_a_in WE";
  attribute X_INTERFACE_INFO of bram_we_a_out_0 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_0 WE";
  attribute X_INTERFACE_INFO of bram_we_a_out_1 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_1 WE";
  attribute X_INTERFACE_INFO of bram_we_a_out_2 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_2 WE";
  attribute X_INTERFACE_INFO of bram_we_a_out_3 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_3 WE";
  attribute X_INTERFACE_INFO of bram_we_a_out_4 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_4 WE";
  attribute X_INTERFACE_INFO of bram_we_a_out_5 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_5 WE";
  attribute X_INTERFACE_INFO of bram_we_a_out_6 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_6 WE";
  attribute X_INTERFACE_INFO of bram_we_a_out_7 : signal is "xilinx.com:interface:bram:1.0 bram_a_out_7 WE";
  attribute X_INTERFACE_INFO of bram_we_b_in : signal is "xilinx.com:interface:bram:1.0 bram_b_in WE";
  attribute X_INTERFACE_INFO of bram_we_b_out_0 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_0 WE";
  attribute X_INTERFACE_INFO of bram_we_b_out_1 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_1 WE";
  attribute X_INTERFACE_INFO of bram_we_b_out_2 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_2 WE";
  attribute X_INTERFACE_INFO of bram_we_b_out_3 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_3 WE";
  attribute X_INTERFACE_INFO of bram_we_b_out_4 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_4 WE";
  attribute X_INTERFACE_INFO of bram_we_b_out_5 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_5 WE";
  attribute X_INTERFACE_INFO of bram_we_b_out_6 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_6 WE";
  attribute X_INTERFACE_INFO of bram_we_b_out_7 : signal is "xilinx.com:interface:bram:1.0 bram_b_out_7 WE";
begin
  \^bram_addr_a_in\(39 downto 0) <= bram_addr_a_in(39 downto 0);
  \^bram_addr_b_in\(39 downto 0) <= bram_addr_b_in(39 downto 0);
  \^bram_clk_a_in\ <= bram_clk_a_in;
  \^bram_clk_b_in\ <= bram_clk_b_in;
  \^bram_din_a_in\(127 downto 0) <= bram_din_a_in(127 downto 0);
  \^bram_din_b_in\(127 downto 0) <= bram_din_b_in(127 downto 0);
  \^bram_dout_a_out_0\(15 downto 0) <= bram_dout_a_out_0(15 downto 0);
  \^bram_dout_a_out_1\(15 downto 0) <= bram_dout_a_out_1(15 downto 0);
  \^bram_dout_a_out_2\(15 downto 0) <= bram_dout_a_out_2(15 downto 0);
  \^bram_dout_a_out_3\(15 downto 0) <= bram_dout_a_out_3(15 downto 0);
  \^bram_dout_a_out_4\(15 downto 0) <= bram_dout_a_out_4(15 downto 0);
  \^bram_dout_a_out_5\(15 downto 0) <= bram_dout_a_out_5(15 downto 0);
  \^bram_dout_a_out_6\(15 downto 0) <= bram_dout_a_out_6(15 downto 0);
  \^bram_dout_a_out_7\(15 downto 0) <= bram_dout_a_out_7(15 downto 0);
  \^bram_dout_b_out_0\(15 downto 0) <= bram_dout_b_out_0(15 downto 0);
  \^bram_dout_b_out_1\(15 downto 0) <= bram_dout_b_out_1(15 downto 0);
  \^bram_dout_b_out_2\(15 downto 0) <= bram_dout_b_out_2(15 downto 0);
  \^bram_dout_b_out_3\(15 downto 0) <= bram_dout_b_out_3(15 downto 0);
  \^bram_dout_b_out_4\(15 downto 0) <= bram_dout_b_out_4(15 downto 0);
  \^bram_dout_b_out_5\(15 downto 0) <= bram_dout_b_out_5(15 downto 0);
  \^bram_dout_b_out_6\(15 downto 0) <= bram_dout_b_out_6(15 downto 0);
  \^bram_dout_b_out_7\(15 downto 0) <= bram_dout_b_out_7(15 downto 0);
  \^bram_en_a_in\ <= bram_en_a_in;
  \^bram_en_b_in\ <= bram_en_b_in;
  \^bram_rst_a_in\ <= bram_rst_a_in;
  \^bram_rst_b_in\ <= bram_rst_b_in;
  \^bram_we_a_in\(15 downto 0) <= bram_we_a_in(15 downto 0);
  \^bram_we_b_in\(15 downto 0) <= bram_we_b_in(15 downto 0);
  bram_addr_a_out_0(39 downto 0) <= \^bram_addr_a_in\(39 downto 0);
  bram_addr_a_out_1(39 downto 0) <= \^bram_addr_a_in\(39 downto 0);
  bram_addr_a_out_2(39 downto 0) <= \^bram_addr_a_in\(39 downto 0);
  bram_addr_a_out_3(39 downto 0) <= \^bram_addr_a_in\(39 downto 0);
  bram_addr_a_out_4(39 downto 0) <= \^bram_addr_a_in\(39 downto 0);
  bram_addr_a_out_5(39 downto 0) <= \^bram_addr_a_in\(39 downto 0);
  bram_addr_a_out_6(39 downto 0) <= \^bram_addr_a_in\(39 downto 0);
  bram_addr_a_out_7(39 downto 0) <= \^bram_addr_a_in\(39 downto 0);
  bram_addr_b_out_0(39 downto 0) <= \^bram_addr_b_in\(39 downto 0);
  bram_addr_b_out_1(39 downto 0) <= \^bram_addr_b_in\(39 downto 0);
  bram_addr_b_out_2(39 downto 0) <= \^bram_addr_b_in\(39 downto 0);
  bram_addr_b_out_3(39 downto 0) <= \^bram_addr_b_in\(39 downto 0);
  bram_addr_b_out_4(39 downto 0) <= \^bram_addr_b_in\(39 downto 0);
  bram_addr_b_out_5(39 downto 0) <= \^bram_addr_b_in\(39 downto 0);
  bram_addr_b_out_6(39 downto 0) <= \^bram_addr_b_in\(39 downto 0);
  bram_addr_b_out_7(39 downto 0) <= \^bram_addr_b_in\(39 downto 0);
  bram_clk_a_out_0 <= \^bram_clk_a_in\;
  bram_clk_a_out_1 <= \^bram_clk_a_in\;
  bram_clk_a_out_2 <= \^bram_clk_a_in\;
  bram_clk_a_out_3 <= \^bram_clk_a_in\;
  bram_clk_a_out_4 <= \^bram_clk_a_in\;
  bram_clk_a_out_5 <= \^bram_clk_a_in\;
  bram_clk_a_out_6 <= \^bram_clk_a_in\;
  bram_clk_a_out_7 <= \^bram_clk_a_in\;
  bram_clk_b_out_0 <= \^bram_clk_b_in\;
  bram_clk_b_out_1 <= \^bram_clk_b_in\;
  bram_clk_b_out_2 <= \^bram_clk_b_in\;
  bram_clk_b_out_3 <= \^bram_clk_b_in\;
  bram_clk_b_out_4 <= \^bram_clk_b_in\;
  bram_clk_b_out_5 <= \^bram_clk_b_in\;
  bram_clk_b_out_6 <= \^bram_clk_b_in\;
  bram_clk_b_out_7 <= \^bram_clk_b_in\;
  bram_din_a_out_0(15 downto 0) <= \^bram_din_a_in\(15 downto 0);
  bram_din_a_out_1(15 downto 0) <= \^bram_din_a_in\(31 downto 16);
  bram_din_a_out_2(15 downto 0) <= \^bram_din_a_in\(47 downto 32);
  bram_din_a_out_3(15 downto 0) <= \^bram_din_a_in\(63 downto 48);
  bram_din_a_out_4(15 downto 0) <= \^bram_din_a_in\(79 downto 64);
  bram_din_a_out_5(15 downto 0) <= \^bram_din_a_in\(95 downto 80);
  bram_din_a_out_6(15 downto 0) <= \^bram_din_a_in\(111 downto 96);
  bram_din_a_out_7(15 downto 0) <= \^bram_din_a_in\(127 downto 112);
  bram_din_b_out_0(15 downto 0) <= \^bram_din_b_in\(15 downto 0);
  bram_din_b_out_1(15 downto 0) <= \^bram_din_b_in\(31 downto 16);
  bram_din_b_out_2(15 downto 0) <= \^bram_din_b_in\(47 downto 32);
  bram_din_b_out_3(15 downto 0) <= \^bram_din_b_in\(63 downto 48);
  bram_din_b_out_4(15 downto 0) <= \^bram_din_b_in\(79 downto 64);
  bram_din_b_out_5(15 downto 0) <= \^bram_din_b_in\(95 downto 80);
  bram_din_b_out_6(15 downto 0) <= \^bram_din_b_in\(111 downto 96);
  bram_din_b_out_7(15 downto 0) <= \^bram_din_b_in\(127 downto 112);
  bram_dout_a_in(127 downto 112) <= \^bram_dout_a_out_7\(15 downto 0);
  bram_dout_a_in(111 downto 96) <= \^bram_dout_a_out_6\(15 downto 0);
  bram_dout_a_in(95 downto 80) <= \^bram_dout_a_out_5\(15 downto 0);
  bram_dout_a_in(79 downto 64) <= \^bram_dout_a_out_4\(15 downto 0);
  bram_dout_a_in(63 downto 48) <= \^bram_dout_a_out_3\(15 downto 0);
  bram_dout_a_in(47 downto 32) <= \^bram_dout_a_out_2\(15 downto 0);
  bram_dout_a_in(31 downto 16) <= \^bram_dout_a_out_1\(15 downto 0);
  bram_dout_a_in(15 downto 0) <= \^bram_dout_a_out_0\(15 downto 0);
  bram_dout_b_in(127 downto 112) <= \^bram_dout_b_out_7\(15 downto 0);
  bram_dout_b_in(111 downto 96) <= \^bram_dout_b_out_6\(15 downto 0);
  bram_dout_b_in(95 downto 80) <= \^bram_dout_b_out_5\(15 downto 0);
  bram_dout_b_in(79 downto 64) <= \^bram_dout_b_out_4\(15 downto 0);
  bram_dout_b_in(63 downto 48) <= \^bram_dout_b_out_3\(15 downto 0);
  bram_dout_b_in(47 downto 32) <= \^bram_dout_b_out_2\(15 downto 0);
  bram_dout_b_in(31 downto 16) <= \^bram_dout_b_out_1\(15 downto 0);
  bram_dout_b_in(15 downto 0) <= \^bram_dout_b_out_0\(15 downto 0);
  bram_en_a_out_0 <= \^bram_en_a_in\;
  bram_en_a_out_1 <= \^bram_en_a_in\;
  bram_en_a_out_2 <= \^bram_en_a_in\;
  bram_en_a_out_3 <= \^bram_en_a_in\;
  bram_en_a_out_4 <= \^bram_en_a_in\;
  bram_en_a_out_5 <= \^bram_en_a_in\;
  bram_en_a_out_6 <= \^bram_en_a_in\;
  bram_en_a_out_7 <= \^bram_en_a_in\;
  bram_en_b_out_0 <= \^bram_en_b_in\;
  bram_en_b_out_1 <= \^bram_en_b_in\;
  bram_en_b_out_2 <= \^bram_en_b_in\;
  bram_en_b_out_3 <= \^bram_en_b_in\;
  bram_en_b_out_4 <= \^bram_en_b_in\;
  bram_en_b_out_5 <= \^bram_en_b_in\;
  bram_en_b_out_6 <= \^bram_en_b_in\;
  bram_en_b_out_7 <= \^bram_en_b_in\;
  bram_rst_a_out_0 <= \^bram_rst_a_in\;
  bram_rst_a_out_1 <= \^bram_rst_a_in\;
  bram_rst_a_out_2 <= \^bram_rst_a_in\;
  bram_rst_a_out_3 <= \^bram_rst_a_in\;
  bram_rst_a_out_4 <= \^bram_rst_a_in\;
  bram_rst_a_out_5 <= \^bram_rst_a_in\;
  bram_rst_a_out_6 <= \^bram_rst_a_in\;
  bram_rst_a_out_7 <= \^bram_rst_a_in\;
  bram_rst_b_out_0 <= \^bram_rst_b_in\;
  bram_rst_b_out_1 <= \^bram_rst_b_in\;
  bram_rst_b_out_2 <= \^bram_rst_b_in\;
  bram_rst_b_out_3 <= \^bram_rst_b_in\;
  bram_rst_b_out_4 <= \^bram_rst_b_in\;
  bram_rst_b_out_5 <= \^bram_rst_b_in\;
  bram_rst_b_out_6 <= \^bram_rst_b_in\;
  bram_rst_b_out_7 <= \^bram_rst_b_in\;
  bram_we_a_out_0(1 downto 0) <= \^bram_we_a_in\(1 downto 0);
  bram_we_a_out_1(1 downto 0) <= \^bram_we_a_in\(3 downto 2);
  bram_we_a_out_2(1 downto 0) <= \^bram_we_a_in\(5 downto 4);
  bram_we_a_out_3(1 downto 0) <= \^bram_we_a_in\(7 downto 6);
  bram_we_a_out_4(1 downto 0) <= \^bram_we_a_in\(9 downto 8);
  bram_we_a_out_5(1 downto 0) <= \^bram_we_a_in\(11 downto 10);
  bram_we_a_out_6(1 downto 0) <= \^bram_we_a_in\(13 downto 12);
  bram_we_a_out_7(1 downto 0) <= \^bram_we_a_in\(15 downto 14);
  bram_we_b_out_0(1 downto 0) <= \^bram_we_b_in\(1 downto 0);
  bram_we_b_out_1(1 downto 0) <= \^bram_we_b_in\(3 downto 2);
  bram_we_b_out_2(1 downto 0) <= \^bram_we_b_in\(5 downto 4);
  bram_we_b_out_3(1 downto 0) <= \^bram_we_b_in\(7 downto 6);
  bram_we_b_out_4(1 downto 0) <= \^bram_we_b_in\(9 downto 8);
  bram_we_b_out_5(1 downto 0) <= \^bram_we_b_in\(11 downto 10);
  bram_we_b_out_6(1 downto 0) <= \^bram_we_b_in\(13 downto 12);
  bram_we_b_out_7(1 downto 0) <= \^bram_we_b_in\(15 downto 14);
end STRUCTURE;
