///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package fetch_unit_axi_vip_0_1_pkg;
import axi_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter fetch_unit_axi_vip_0_1_VIP_PROTOCOL           = 0;
      parameter fetch_unit_axi_vip_0_1_VIP_READ_WRITE_MODE    = "READ_WRITE";
      parameter fetch_unit_axi_vip_0_1_VIP_INTERFACE_MODE     = 2;
      parameter fetch_unit_axi_vip_0_1_VIP_ADDR_WIDTH         = 32;
      parameter fetch_unit_axi_vip_0_1_VIP_DATA_WIDTH         = 128;
      parameter fetch_unit_axi_vip_0_1_VIP_ID_WIDTH           = 1;
      parameter fetch_unit_axi_vip_0_1_VIP_AWUSER_WIDTH       = 1;
      parameter fetch_unit_axi_vip_0_1_VIP_ARUSER_WIDTH       = 1;
      parameter fetch_unit_axi_vip_0_1_VIP_RUSER_WIDTH        = 1;
      parameter fetch_unit_axi_vip_0_1_VIP_WUSER_WIDTH        = 1;
      parameter fetch_unit_axi_vip_0_1_VIP_BUSER_WIDTH        = 1;
      parameter fetch_unit_axi_vip_0_1_VIP_SUPPORTS_NARROW    = 0;
      parameter fetch_unit_axi_vip_0_1_VIP_HAS_BURST          = 1;
      parameter fetch_unit_axi_vip_0_1_VIP_HAS_LOCK           = 1;
      parameter fetch_unit_axi_vip_0_1_VIP_HAS_CACHE          = 1;
      parameter fetch_unit_axi_vip_0_1_VIP_HAS_REGION         = 0;
      parameter fetch_unit_axi_vip_0_1_VIP_HAS_QOS            = 1;
      parameter fetch_unit_axi_vip_0_1_VIP_HAS_PROT           = 1;
      parameter fetch_unit_axi_vip_0_1_VIP_HAS_WSTRB          = 1;
      parameter fetch_unit_axi_vip_0_1_VIP_HAS_BRESP          = 1;
      parameter fetch_unit_axi_vip_0_1_VIP_HAS_RRESP          = 1;
      parameter fetch_unit_axi_vip_0_1_VIP_HAS_ACLKEN         = 0;
      parameter fetch_unit_axi_vip_0_1_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////


typedef axi_slv_agent #(fetch_unit_axi_vip_0_1_VIP_PROTOCOL, 
                        fetch_unit_axi_vip_0_1_VIP_ADDR_WIDTH,
                        fetch_unit_axi_vip_0_1_VIP_DATA_WIDTH,
                        fetch_unit_axi_vip_0_1_VIP_DATA_WIDTH,
                        fetch_unit_axi_vip_0_1_VIP_ID_WIDTH,
                        fetch_unit_axi_vip_0_1_VIP_ID_WIDTH,
                        fetch_unit_axi_vip_0_1_VIP_AWUSER_WIDTH, 
                        fetch_unit_axi_vip_0_1_VIP_WUSER_WIDTH, 
                        fetch_unit_axi_vip_0_1_VIP_BUSER_WIDTH, 
                        fetch_unit_axi_vip_0_1_VIP_ARUSER_WIDTH,
                        fetch_unit_axi_vip_0_1_VIP_RUSER_WIDTH, 
                        fetch_unit_axi_vip_0_1_VIP_SUPPORTS_NARROW, 
                        fetch_unit_axi_vip_0_1_VIP_HAS_BURST,
                        fetch_unit_axi_vip_0_1_VIP_HAS_LOCK,
                        fetch_unit_axi_vip_0_1_VIP_HAS_CACHE,
                        fetch_unit_axi_vip_0_1_VIP_HAS_REGION,
                        fetch_unit_axi_vip_0_1_VIP_HAS_PROT,
                        fetch_unit_axi_vip_0_1_VIP_HAS_QOS,
                        fetch_unit_axi_vip_0_1_VIP_HAS_WSTRB,
                        fetch_unit_axi_vip_0_1_VIP_HAS_BRESP,
                        fetch_unit_axi_vip_0_1_VIP_HAS_RRESP,
                        fetch_unit_axi_vip_0_1_VIP_HAS_ARESETN) fetch_unit_axi_vip_0_1_slv_t;

typedef axi_slv_mem_agent #(fetch_unit_axi_vip_0_1_VIP_PROTOCOL, 
                        fetch_unit_axi_vip_0_1_VIP_ADDR_WIDTH,
                        fetch_unit_axi_vip_0_1_VIP_DATA_WIDTH,
                        fetch_unit_axi_vip_0_1_VIP_DATA_WIDTH,
                        fetch_unit_axi_vip_0_1_VIP_ID_WIDTH,
                        fetch_unit_axi_vip_0_1_VIP_ID_WIDTH,
                        fetch_unit_axi_vip_0_1_VIP_AWUSER_WIDTH, 
                        fetch_unit_axi_vip_0_1_VIP_WUSER_WIDTH, 
                        fetch_unit_axi_vip_0_1_VIP_BUSER_WIDTH, 
                        fetch_unit_axi_vip_0_1_VIP_ARUSER_WIDTH,
                        fetch_unit_axi_vip_0_1_VIP_RUSER_WIDTH, 
                        fetch_unit_axi_vip_0_1_VIP_SUPPORTS_NARROW, 
                        fetch_unit_axi_vip_0_1_VIP_HAS_BURST,
                        fetch_unit_axi_vip_0_1_VIP_HAS_LOCK,
                        fetch_unit_axi_vip_0_1_VIP_HAS_CACHE,
                        fetch_unit_axi_vip_0_1_VIP_HAS_REGION,
                        fetch_unit_axi_vip_0_1_VIP_HAS_PROT,
                        fetch_unit_axi_vip_0_1_VIP_HAS_QOS,
                        fetch_unit_axi_vip_0_1_VIP_HAS_WSTRB,
                        fetch_unit_axi_vip_0_1_VIP_HAS_BRESP,
                        fetch_unit_axi_vip_0_1_VIP_HAS_RRESP,
                        fetch_unit_axi_vip_0_1_VIP_HAS_ARESETN) fetch_unit_axi_vip_0_1_slv_mem_t;
                        
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      fetch_unit_axi_vip_0_1_slv_t  fetch_unit_axi_vip_0_1_slv;
//      initial begin : START_fetch_unit_axi_vip_0_1_SLAVE
//        fetch_unit_axi_vip_0_1_slv = new("fetch_unit_axi_vip_0_1_slv", `fetch_unit_axi_vip_0_1_PATH_TO_INTERFACE);
//        fetch_unit_axi_vip_0_1_slv.start_slave();
//      end

endpackage : fetch_unit_axi_vip_0_1_pkg
