webtalk_init -webtalk_dir /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.sim/sim_1/behav/xsim/xsim.dir/TB_fetch_unit_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Oct 10 13:54:57 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211402415_1777528373_210693619_045" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c945f6c7-a29a-430e-b91c-7fe54653876c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b700f324250746cfb9eb35d61782e182" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "40" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1000.061 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "99.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.10_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "147776_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3957574832 -regid "211402415_1777528373_210693619_045" -xml /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.sim/sim_1/behav/xsim/xsim.dir/TB_fetch_unit_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.sim/sim_1/behav/xsim/xsim.dir/TB_fetch_unit_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.sim/sim_1/behav/xsim/xsim.dir/TB_fetch_unit_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
