///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package design_relcache_axi_vip_1_1_pkg;
import axi_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter design_relcache_axi_vip_1_1_VIP_PROTOCOL           = 0;
      parameter design_relcache_axi_vip_1_1_VIP_READ_WRITE_MODE    = "READ_WRITE";
      parameter design_relcache_axi_vip_1_1_VIP_INTERFACE_MODE     = 2;
      parameter design_relcache_axi_vip_1_1_VIP_ADDR_WIDTH         = 40;
      parameter design_relcache_axi_vip_1_1_VIP_DATA_WIDTH         = 128;
      parameter design_relcache_axi_vip_1_1_VIP_ID_WIDTH           = 0;
      parameter design_relcache_axi_vip_1_1_VIP_AWUSER_WIDTH       = 1;
      parameter design_relcache_axi_vip_1_1_VIP_ARUSER_WIDTH       = 1;
      parameter design_relcache_axi_vip_1_1_VIP_RUSER_WIDTH        = 0;
      parameter design_relcache_axi_vip_1_1_VIP_WUSER_WIDTH        = 0;
      parameter design_relcache_axi_vip_1_1_VIP_BUSER_WIDTH        = 1;
      parameter design_relcache_axi_vip_1_1_VIP_SUPPORTS_NARROW    = 0;
      parameter design_relcache_axi_vip_1_1_VIP_HAS_BURST          = 1;
      parameter design_relcache_axi_vip_1_1_VIP_HAS_LOCK           = 1;
      parameter design_relcache_axi_vip_1_1_VIP_HAS_CACHE          = 1;
      parameter design_relcache_axi_vip_1_1_VIP_HAS_REGION         = 0;
      parameter design_relcache_axi_vip_1_1_VIP_HAS_QOS            = 1;
      parameter design_relcache_axi_vip_1_1_VIP_HAS_PROT           = 1;
      parameter design_relcache_axi_vip_1_1_VIP_HAS_WSTRB          = 1;
      parameter design_relcache_axi_vip_1_1_VIP_HAS_BRESP          = 1;
      parameter design_relcache_axi_vip_1_1_VIP_HAS_RRESP          = 1;
      parameter design_relcache_axi_vip_1_1_VIP_HAS_ACLKEN         = 0;
      parameter design_relcache_axi_vip_1_1_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////


typedef axi_slv_agent #(design_relcache_axi_vip_1_1_VIP_PROTOCOL, 
                        design_relcache_axi_vip_1_1_VIP_ADDR_WIDTH,
                        design_relcache_axi_vip_1_1_VIP_DATA_WIDTH,
                        design_relcache_axi_vip_1_1_VIP_DATA_WIDTH,
                        design_relcache_axi_vip_1_1_VIP_ID_WIDTH,
                        design_relcache_axi_vip_1_1_VIP_ID_WIDTH,
                        design_relcache_axi_vip_1_1_VIP_AWUSER_WIDTH, 
                        design_relcache_axi_vip_1_1_VIP_WUSER_WIDTH, 
                        design_relcache_axi_vip_1_1_VIP_BUSER_WIDTH, 
                        design_relcache_axi_vip_1_1_VIP_ARUSER_WIDTH,
                        design_relcache_axi_vip_1_1_VIP_RUSER_WIDTH, 
                        design_relcache_axi_vip_1_1_VIP_SUPPORTS_NARROW, 
                        design_relcache_axi_vip_1_1_VIP_HAS_BURST,
                        design_relcache_axi_vip_1_1_VIP_HAS_LOCK,
                        design_relcache_axi_vip_1_1_VIP_HAS_CACHE,
                        design_relcache_axi_vip_1_1_VIP_HAS_REGION,
                        design_relcache_axi_vip_1_1_VIP_HAS_PROT,
                        design_relcache_axi_vip_1_1_VIP_HAS_QOS,
                        design_relcache_axi_vip_1_1_VIP_HAS_WSTRB,
                        design_relcache_axi_vip_1_1_VIP_HAS_BRESP,
                        design_relcache_axi_vip_1_1_VIP_HAS_RRESP,
                        design_relcache_axi_vip_1_1_VIP_HAS_ARESETN) design_relcache_axi_vip_1_1_slv_t;

typedef axi_slv_mem_agent #(design_relcache_axi_vip_1_1_VIP_PROTOCOL, 
                        design_relcache_axi_vip_1_1_VIP_ADDR_WIDTH,
                        design_relcache_axi_vip_1_1_VIP_DATA_WIDTH,
                        design_relcache_axi_vip_1_1_VIP_DATA_WIDTH,
                        design_relcache_axi_vip_1_1_VIP_ID_WIDTH,
                        design_relcache_axi_vip_1_1_VIP_ID_WIDTH,
                        design_relcache_axi_vip_1_1_VIP_AWUSER_WIDTH, 
                        design_relcache_axi_vip_1_1_VIP_WUSER_WIDTH, 
                        design_relcache_axi_vip_1_1_VIP_BUSER_WIDTH, 
                        design_relcache_axi_vip_1_1_VIP_ARUSER_WIDTH,
                        design_relcache_axi_vip_1_1_VIP_RUSER_WIDTH, 
                        design_relcache_axi_vip_1_1_VIP_SUPPORTS_NARROW, 
                        design_relcache_axi_vip_1_1_VIP_HAS_BURST,
                        design_relcache_axi_vip_1_1_VIP_HAS_LOCK,
                        design_relcache_axi_vip_1_1_VIP_HAS_CACHE,
                        design_relcache_axi_vip_1_1_VIP_HAS_REGION,
                        design_relcache_axi_vip_1_1_VIP_HAS_PROT,
                        design_relcache_axi_vip_1_1_VIP_HAS_QOS,
                        design_relcache_axi_vip_1_1_VIP_HAS_WSTRB,
                        design_relcache_axi_vip_1_1_VIP_HAS_BRESP,
                        design_relcache_axi_vip_1_1_VIP_HAS_RRESP,
                        design_relcache_axi_vip_1_1_VIP_HAS_ARESETN) design_relcache_axi_vip_1_1_slv_mem_t;
                        
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      design_relcache_axi_vip_1_1_slv_t  design_relcache_axi_vip_1_1_slv;
//      initial begin : START_design_relcache_axi_vip_1_1_SLAVE
//        design_relcache_axi_vip_1_1_slv = new("design_relcache_axi_vip_1_1_slv", `design_relcache_axi_vip_1_1_PATH_TO_INTERFACE);
//        design_relcache_axi_vip_1_1_slv.start_slave();
//      end

endpackage : design_relcache_axi_vip_1_1_pkg
