# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+/RatMem/RatMem.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_1/design_1_system_ila_1_1.xci
# IP: The module: 'design_1_system_ila_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+/RatMem/RatMem.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_1/bd_0/bd_f69c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f69c || ORIG_REF_NAME==bd_f69c} -quiet] -quiet

# IP: /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+/RatMem/RatMem.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_1/bd_0/ip/ip_0/bd_f69c_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f69c_ila_lib_0 || ORIG_REF_NAME==bd_f69c_ila_lib_0} -quiet] -quiet

# XDC: /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+/RatMem/RatMem.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f69c_ila_lib_0 || ORIG_REF_NAME==bd_f69c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+/RatMem/RatMem.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f69c_ila_lib_0 || ORIG_REF_NAME==bd_f69c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+/RatMem/RatMem.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_1/bd_0/ip/ip_0/bd_f69c_ila_lib_0_ooc.xdc

# XDC: /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+/RatMem/RatMem.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_1/bd_0/bd_f69c_ooc.xdc

# XDC: /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+/RatMem/RatMem.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_1/design_1_system_ila_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_1_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+/RatMem/RatMem.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_1/design_1_system_ila_1_1.xci
# IP: The module: 'design_1_system_ila_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+/RatMem/RatMem.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_1/bd_0/bd_f69c.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f69c || ORIG_REF_NAME==bd_f69c} -quiet] -quiet

# IP: /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+/RatMem/RatMem.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_1/bd_0/ip/ip_0/bd_f69c_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f69c_ila_lib_0 || ORIG_REF_NAME==bd_f69c_ila_lib_0} -quiet] -quiet

# XDC: /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+/RatMem/RatMem.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f69c_ila_lib_0 || ORIG_REF_NAME==bd_f69c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+/RatMem/RatMem.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f69c_ila_lib_0 || ORIG_REF_NAME==bd_f69c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+/RatMem/RatMem.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_1/bd_0/ip/ip_0/bd_f69c_ila_lib_0_ooc.xdc

# XDC: /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+/RatMem/RatMem.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_1/bd_0/bd_f69c_ooc.xdc

# XDC: /home/ro0zkhosh/RelationalMem/RelationalMem/ZYNQ_ULTRASCARE+/RatMem/RatMem.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_1/design_1_system_ila_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
