# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/design_2_system_ila_0_1.xci
# IP: The module: 'design_2_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/bd_c78d.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d || ORIG_REF_NAME==bd_c78d} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_0/bd_c78d_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_ila_lib_0 || ORIG_REF_NAME==bd_c78d_ila_lib_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_1/bd_c78d_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_g_inst_0 || ORIG_REF_NAME==bd_c78d_g_inst_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_2/bd_c78d_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_0_aw_0 || ORIG_REF_NAME==bd_c78d_slot_0_aw_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_3/bd_c78d_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_0_w_0 || ORIG_REF_NAME==bd_c78d_slot_0_w_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_4/bd_c78d_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_0_b_0 || ORIG_REF_NAME==bd_c78d_slot_0_b_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_5/bd_c78d_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_0_ar_0 || ORIG_REF_NAME==bd_c78d_slot_0_ar_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_6/bd_c78d_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_0_r_0 || ORIG_REF_NAME==bd_c78d_slot_0_r_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_7/bd_c78d_slot_1_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_1_aw_0 || ORIG_REF_NAME==bd_c78d_slot_1_aw_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_8/bd_c78d_slot_1_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_1_w_0 || ORIG_REF_NAME==bd_c78d_slot_1_w_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_9/bd_c78d_slot_1_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_1_b_0 || ORIG_REF_NAME==bd_c78d_slot_1_b_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_10/bd_c78d_slot_1_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_1_ar_0 || ORIG_REF_NAME==bd_c78d_slot_1_ar_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_11/bd_c78d_slot_1_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_1_r_0 || ORIG_REF_NAME==bd_c78d_slot_1_r_0} -quiet] -quiet

# XDC: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c78d_ila_lib_0 || ORIG_REF_NAME==bd_c78d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c78d_ila_lib_0 || ORIG_REF_NAME==bd_c78d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_0/bd_c78d_ila_lib_0_ooc.xdc

# XDC: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/bd_c78d_ooc.xdc

# XDC: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/design_2_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/design_2_system_ila_0_1.xci
# IP: The module: 'design_2_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/bd_c78d.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d || ORIG_REF_NAME==bd_c78d} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_0/bd_c78d_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_ila_lib_0 || ORIG_REF_NAME==bd_c78d_ila_lib_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_1/bd_c78d_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_g_inst_0 || ORIG_REF_NAME==bd_c78d_g_inst_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_2/bd_c78d_slot_0_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_0_aw_0 || ORIG_REF_NAME==bd_c78d_slot_0_aw_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_3/bd_c78d_slot_0_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_0_w_0 || ORIG_REF_NAME==bd_c78d_slot_0_w_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_4/bd_c78d_slot_0_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_0_b_0 || ORIG_REF_NAME==bd_c78d_slot_0_b_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_5/bd_c78d_slot_0_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_0_ar_0 || ORIG_REF_NAME==bd_c78d_slot_0_ar_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_6/bd_c78d_slot_0_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_0_r_0 || ORIG_REF_NAME==bd_c78d_slot_0_r_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_7/bd_c78d_slot_1_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_1_aw_0 || ORIG_REF_NAME==bd_c78d_slot_1_aw_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_8/bd_c78d_slot_1_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_1_w_0 || ORIG_REF_NAME==bd_c78d_slot_1_w_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_9/bd_c78d_slot_1_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_1_b_0 || ORIG_REF_NAME==bd_c78d_slot_1_b_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_10/bd_c78d_slot_1_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_1_ar_0 || ORIG_REF_NAME==bd_c78d_slot_1_ar_0} -quiet] -quiet

# IP: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_11/bd_c78d_slot_1_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c78d_slot_1_r_0 || ORIG_REF_NAME==bd_c78d_slot_1_r_0} -quiet] -quiet

# XDC: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c78d_ila_lib_0 || ORIG_REF_NAME==bd_c78d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c78d_ila_lib_0 || ORIG_REF_NAME==bd_c78d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/ip/ip_0/bd_c78d_ila_lib_0_ooc.xdc

# XDC: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/bd_0/bd_c78d_ooc.xdc

# XDC: /home/renato/RelationalMem/ZYNQ_ULTRASCARE+_bkp_sep_20/RatMem/RatMem.srcs/sources_1/bd/design_2/ip/design_2_system_ila_0_1_1/design_2_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
