# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/design_2_wrapper_2.xdc

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_zynq_ultra_ps_e_0_0/design_2_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_2_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_ps8_0_99M_0/design_2_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_rst_ps8_0_99M_0 || ORIG_REF_NAME==design_2_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_AXI_PerfectTranslator_0_0/design_2_AXI_PerfectTranslator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_AXI_PerfectTranslator_0_0 || ORIG_REF_NAME==design_2_AXI_PerfectTranslator_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_system_ila_0_0_2/design_2_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_system_ila_0_0 || ORIG_REF_NAME==design_2_system_ila_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_RelationalCache_0_0/design_2_RelationalCache_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_RelationalCache_0_0 || ORIG_REF_NAME==design_2_RelationalCache_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ila_0_0_2/design_2_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ila_0_0 || ORIG_REF_NAME==design_2_ila_0_0} -quiet] -quiet

# XDC: bd/design_2/design_2_ooc.xdc
